// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationsController from "./animations_controller"
application.register("animations", AnimationsController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
